# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-26 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='\u8d44\u4ea7\u540d')),
                ('sn', models.CharField(max_length=128, unique=True, verbose_name='\u8d44\u4ea7sn\u53f7')),
                ('asset_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='\u8bbe\u5907\u7ba1\u7406IP')),
                ('asset_postion', models.IntegerField(blank=True, null=True, verbose_name='\u673a\u67dc\u4f4d')),
                ('trade_date', models.DateField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u65e5\u671f')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u4ef7\u683c(\u5143)')),
                ('asset_status', models.IntegerField(choices=[(0, '\u5728\u7ebf'), (1, '\u4e0b\u7ebf'), (2, '\u6545\u969c'), (3, '\u5907\u7528'), (4, '\u672a\u77e5')], verbose_name='\u8d44\u4ea7\u72b6\u6001')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u8d44\u4ea7\u521b\u5efa\u65f6\u95f4')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u8d44\u4ea7\u53d8\u66f4\u65f6\u95f4')),
                ('asset_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d44\u4ea7\u8d1f\u8d23\u4eba')),
            ],
            options={
                'db_table': 'asset',
                'verbose_name': '\u8d44\u4ea7\u4fe1\u606f',
                'verbose_name_plural': '\u8d44\u4ea7\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('acid', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=30, unique=True, verbose_name='\u8d44\u4ea7\u7c7b\u522b\u5206\u7c7b')),
            ],
            options={
                'db_table': 'assetcategory',
                'verbose_name': '\u8d44\u4ea7\u7c7b\u522b\u5206\u7c7b\u4fe1\u606f',
                'verbose_name_plural': '\u8d44\u4ea7\u7c7b\u522b\u5206\u7c7b\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('acid', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50, unique=True, verbose_name='\u8d44\u4ea7\u7c7b\u522b')),
                ('assetcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.AssetCategory', verbose_name='\u8d44\u4ea7\u7c7b\u522b\u5206\u7c7b')),
            ],
            options={
                'db_table': 'assetclass',
                'verbose_name': '\u8d44\u4ea7\u7c7b\u522b',
                'verbose_name_plural': '\u8d44\u4ea7\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='BusinessLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='\u4e1a\u52a1\u7ebf\u540d')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'businessline',
                'verbose_name': '\u4e1a\u52a1\u7ebf\u8868',
                'verbose_name_plural': '\u4e1a\u52a1\u7ebf\u8868',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('cabid', models.AutoField(primary_key=True, serialize=False)),
                ('cabinet', models.IntegerField(verbose_name='\u673a\u67dc\u53f7')),
            ],
            options={
                'db_table': 'cabinet',
                'verbose_name': '\u673a\u67dc\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u67dc\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('idc_id', models.AutoField(primary_key=True, serialize=False)),
                ('idcname', models.CharField(max_length=20, verbose_name='idc\u540d')),
            ],
            options={
                'db_table': 'idc',
                'verbose_name': 'idc\u540d',
                'verbose_name_plural': 'idc\u540d',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('rackid', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.IntegerField(verbose_name='\u673a\u67b6\u53f7')),
            ],
            options={
                'db_table': 'rack',
                'verbose_name': '\u673a\u67b6\u4fe1\u606f',
                'verbose_name_plural': '\u673a\u67b6\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ServerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668\u673a\u623f\u540d')),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='\u673a\u623f\u6807\u7b7e\u540d')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.IDC', verbose_name='\u6240\u5c5eIDC')),
            ],
            options={
                'db_table': 'serverroom',
                'verbose_name': '\u673a\u623f\u540d',
                'verbose_name_plural': '\u673a\u623f\u540d',
            },
        ),
        migrations.AddField(
            model_name='rack',
            name='serverroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.ServerRoom', verbose_name='\u6240\u5c5e\u673a\u623f'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='rack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Rack', verbose_name='\u6240\u5c5e\u673a\u67b6'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Cabinet', verbose_name='\u673a\u67dc\u53f7'),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.AssetClass', verbose_name='\u8d44\u4ea7\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='asset',
            name='businessline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.BusinessLine', verbose_name='\u6240\u5c5e\u4e1a\u52a1\u7ebf'),
        ),
    ]
